server:
  port: 8888
  address: https://apigateway-service.herokuapp.com/
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: ${server.address}
    ip-address: ${server.address}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
