server:
  port: 8888
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-spring-app.herokuapp.com/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
